version: '3.7'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go-app-network

  url-shortener-app:
    build: .
    hostname: url-shortener-service
    environment:
      - ENV=prod
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - go-app-network

networks:
  go-app-network:
    driver: bridge

volumes:
  postgres_data:
